# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
loader_version=0.16.10
yarn_mappings=1.21+build.9
minecraft_version=1.21
fabric_version=0.102.0+1.21

# Mod Properties
mod_version = 3.0.0
maven_group=net.myles124.allstackablecontinued
archives_base_name=AllStackableContinued


